[package]
name = "sandbox"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
rogueworks-core = { path = "../rogueworks-core" }
rogueworks-diagnostics = { path = "../rogueworks-diagnostics" }
