[package]
name = "rogueworks-core"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
serde = ["dep:serde"]
metrics = []

[dependencies]
legion = "0.4.0"
rand = "0.8"
tracing = "0.1"
thiserror = "1"
serde = { version = "1.0", features = ["derive"], optional = true }
