[package]
name = "rogueworks-map"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
serde = ["dep:serde"]

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }
bitflags = "1.3"
