[book]
title = "Rogueworks"
authors = ["You"]
language = "en"
multilingual = false
src = "src"

[build]
create-missing = true

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = ""
additional-css = []
